[WIP] Frontend forms / Login
hercules-ci/hercules pull request #54
Opened 2017-11-05 15:25 UTC by phile314

I have been playing a bit around with the elm code. When I tried to get the login form working, I had to actually make some quite big changes as I didn't want to put all ``Msg`` constructors into the top-level ``Msg``. I mostly followed the example from https://github.com/rtfeldman/elm-spa-example to get it working.

This is a work-in-progress, but it would be good to discuss what your plans for the hercules frontend and hercules itself are?

2017-11-06 18:44 UTC, expipiplus1 commented
@domenkozar's the person for the frontend stuff!

2017-11-08 10:19 UTC, domenkozar requested changes
Looks great progress! Do you need some help going forward?

2017-11-08 10:19 UTC, domenkozar commented on frontend/src/Models.elm
> +    | JobsetPage2 String String
Why not just `JobsetPage`? :)

2017-11-08 10:19 UTC, domenkozar commented on frontend/src/Update.elm
> +        ( _, _ ) ->
I'd prefer not to have catch-all, to actually error out if something is missing.

2017-11-08 11:52 UTC, phile314-fh commented
So the big architectural change is really with the new ``Msg`` with the sub-msg types inside the page. Also the new ``Page`` type and the corresponding changes in the routing/update functions. Do you think this is going in the right direction? (This stuff is quite painful to change, so that why I am bringing this up now even though this PR is still work-in-progress.)

I think I will finish up the Login page, with the goal to merge this as a first step. Second part probably would be to implement e.g. the Jobset display with the actual REST API.

2017-11-08 15:02 UTC, domenkozar commented
@phile314 it does go in the right direction. Ideally, each component would be self-contained. And then routing functions can work on any component independently. Good work!

2017-11-09 19:56 UTC, phile314 commented on frontend/src/Update.elm
> +        ( _, _ ) ->
Hm, I tried doing that but then the compiler complains that there are unhandled cases:
```
    (Msg.LoginMsg _, Models.HomePage)
    (Msg.LoginMsg _, Models.ProjectPage _)
    (Msg.LoginMsg _, Models.NewProjectPage)
    (Msg.LoginMsg _, Models.JobsetPage _ _)
```
This are basically impossible cases, but the compiler doesn't see that. What about putting a Debug.crash inside the catch-all instead?

2018-11-06 08:04 UTC, closed without merging